#
# Makefile for the LGE platform device drivers.
#
#platform.team@lge.com	2011.01

EXTRA_CFLAGS += -Ilge/include

obj-y += camera/
obj-y += input/
obj-y += misc/
#obj-y += power/
obj-y += display/
obj-y += audio/

# ella.hwang@lge.com	2011.05.05
obj-y += broadcast/

obj-y += felica/
obj-y += mhl_v1/

obj-y += device_lge.o
