#platform.team@lge.com	2011.01

EXTRA_CFLAGS += -Iarch/arm/mach-msm
EXTRA_CFLAGS += -Iarch/arm/mach-msm/qdsp6v2
EXTRA_CFLAGS += -Ilge/include

obj-$(CONFIG_MACH_LGE_I_BOARD_ATNT)	+= board_i_atnt.o
obj-$(CONFIG_MACH_LGE_I_BOARD_ATNT)	+= platform_i_atnt_bt.o
obj-$(CONFIG_MACH_LGE_I_BOARD_ATNT)	+= platform_i_atnt_camera.o
obj-$(CONFIG_MACH_LGE_I_BOARD_ATNT)	+= platform_i_atnt_input.o
obj-$(CONFIG_MACH_LGE_I_BOARD_ATNT)	+= platform_i_atnt_misc.o
obj-$(CONFIG_MACH_LGE_I_BOARD_ATNT)	+= platform_i_atnt_mmc.o
obj-$(CONFIG_MACH_LGE_I_BOARD_ATNT)	+= platform_i_atnt_panel.o
obj-$(CONFIG_MACH_LGE_I_BOARD_ATNT)	+= platform_i_atnt_snd.o
obj-$(CONFIG_MACH_LGE_I_BOARD_ATNT)	+= gpiomux_i_atnt.o
obj-$(CONFIG_MACH_LGE_I_BOARD_ATNT)	+= devices_i_atnt.o
