#
# Makefile for the Misc drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_LGE_MUIC_TS5USBA33402)+= muic.o

obj-$(CONFIG_ANDROID_VIBRATOR)+= android_vibrator.o
obj-$(CONFIG_LGE_ISA1200)+= lge_isa1200.o
