#platform.team@lge.com	2011.01

EXTRA_CFLAGS += -Iarch/arm/mach-msm
EXTRA_CFLAGS += -Iarch/arm/mach-msm/qdsp6v2
EXTRA_CFLAGS += -Ilge/include

obj-$(CONFIG_MACH_LGE_HDK_8x60)	+= board_hdk_8x60.o
obj-$(CONFIG_MACH_LGE_HDK_8x60)	+= platform_hdk_8x60_bt.o
obj-$(CONFIG_MACH_LGE_HDK_8x60)	+= platform_hdk_8x60_camera.o
obj-$(CONFIG_MACH_LGE_HDK_8x60)	+= platform_hdk_8x60_input.o
obj-$(CONFIG_MACH_LGE_HDK_8x60)	+= platform_hdk_8x60_misc.o
obj-$(CONFIG_MACH_LGE_HDK_8x60)	+= platform_hdk_8x60_mmc.o
obj-$(CONFIG_MACH_LGE_HDK_8x60)	+= platform_hdk_8x60_panel.o
obj-$(CONFIG_MACH_LGE_HDK_8x60)	+= platform_hdk_8x60_snd.o
obj-$(CONFIG_MACH_LGE_HDK_8x60)	+= gpiomux_hdk_8x60.o
obj-$(CONFIG_MACH_LGE_HDK_8x60)	+= devices_hdk_8x60.o

